main_svc
thisisaleksander/java-explore-with-me pull request #4
Opened 2023-08-10 23:36 UTC by thisisaleksander

2023-08-11 19:23 UTC, krylov-sergey-sergeevich commented
Есть мысли почему сборка падает, вторая вон красная?

2023-08-11 19:29 UTC, krylov-sergey-sergeevich requested changes
Привет, посмотрел, вроде неплохо.

Давай обсудим билд и мелочи

2023-08-11 19:29 UTC, krylov-sergey-sergeevich commented on main/src/main/resources/schema.sql
> +    unique (email),
рекомендую все же имена давать для таких констрейнтов

2023-08-11 19:29 UTC, krylov-sergey-sergeevich commented on statistics/statistics-client/src/main/java/ru/practicum/StatisticsClient.java
> +                .uriTemplateHandler(new DefaultUriBuilderFactory("http://stats-server:9090"))
лучше не хардкодить путь а через переменные приложения определять

2023-08-11 19:29 UTC, krylov-sergey-sergeevich commented on statistics/statistics-client/src/main/java/ru/practicum/StatisticsClient.java
> +    public static final String START = "2000-01-01 01:01:01";
Если нужны минимальные и макс даты то вроде что то вроде дефолтных LocalDateTime.MIN / MAX

2023-08-11 21:33 UTC, thisisaleksander commented on main/src/main/resources/schema.sql
> +    unique (email),
добавил

2023-08-11 21:34 UTC, thisisaleksander commented on statistics/statistics-client/src/main/java/ru/practicum/StatisticsClient.java
> +                .uriTemplateHandler(new DefaultUriBuilderFactory("http://stats-server:9090"))
поправил

2023-08-11 21:39 UTC, thisisaleksander commented on statistics/statistics-client/src/main/java/ru/practicum/StatisticsClient.java
> +    public static final String START = "2000-01-01 01:01:01";
поправил

2023-08-13 15:31 UTC, krylov-sergey-sergeevich requested changes
Примеры скинул

2023-08-13 15:31 UTC, krylov-sergey-sergeevich commented on statistics/general-dto/pom.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>stats</artifactId>
        <groupId>ru.practicum</groupId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>stats-dto</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-json</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
        </dependency>
    </dependencies>

</project>
```

2023-08-13 15:31 UTC, krylov-sergey-sergeevich commented on statistics/statistics-client/pom.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>stats</artifactId>
        <groupId>ru.practicum</groupId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>stats-client</artifactId>

    <dependencies>
        <dependency>
            <groupId>ru.practicum</groupId>
            <artifactId>stats-dto</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>

</project>
```

2023-08-13 15:31 UTC, krylov-sergey-sergeevich commented on statistics/statistics-server/pom.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>stats</artifactId>
        <groupId>ru.practicum</groupId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>stats-server</artifactId>

    <dependencies>
        <dependency>
            <groupId>ru.practicum</groupId>
            <artifactId>stats-dto</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jdbc</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <jvmArguments>-Dspring.application.admin.enabled=true</jvmArguments>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
```

2023-08-13 15:31 UTC, krylov-sergey-sergeevich commented on statistics/statistics-server/pom.xml
Как пример
```
FROM eclipse-temurin:11-jre-jammy
VOLUME /tmp
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar /app.jar ${0} ${@}"]
```

2023-08-14 18:56 UTC, krylov-sergey-sergeevich approved these changes
Привет, похоже на правду - зачет

- Есть повторяющиеся блоки кода, но мучать с их оптимизацией не буду

2023-08-14 18:56 UTC, krylov-sergey-sergeevich commented on main-service/pom.xml
> +            <artifactId>javax.ws.rs-api</artifactId>
для чего это?

2023-08-16 14:13 UTC, merged