Feature comments
thisisaleksander/java-explore-with-me pull request #5
Opened 2023-08-16 14:32 UTC by thisisaleksander

2023-08-17 14:31 UTC, krylov-sergey-sergeevich requested changes
Привет, давай чуть чуть поправим

- В исключения добавить больше информации айдишники где возможно
- Наверно когда "User is not commentator" это уже смахивает на SecurityException а не Validation - но тут не критично


Буду ждать с правками =)

2023-08-17 14:31 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/ewm/comment/mapper/CommentMapper.java
> +    static final DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
В DateUtils я бы вынес

2023-08-17 14:31 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/ewm/comment/service/CommentServiceImpl.java
> +        Comment comment = commentRepository.findById(commentId).orElseThrow(() -> new NotFoundException("Comment not found"));
А какой коммент не найден? В исключение надо указать айдишник еще кого ищем

2023-08-17 14:31 UTC, krylov-sergey-sergeevich commented on main-service/src/main/resources/schema.sql
not null маловато

2023-08-18 11:32 UTC, thisisaleksander commented on main-service/src/main/java/ru/practicum/ewm/comment/mapper/CommentMapper.java
> +    static final DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Добавил и вынес все туда

2023-08-18 11:32 UTC, thisisaleksander commented on main-service/src/main/java/ru/practicum/ewm/comment/service/CommentServiceImpl.java
> +        commentDto.setStatus("WAITING");
Вроде да

2023-08-18 12:05 UTC, thisisaleksander commented on main-service/src/main/java/ru/practicum/ewm/comment/service/CommentServiceImpl.java
> +        Comment comment = commentRepository.findById(commentId).orElseThrow(() -> new NotFoundException("Comment not found"));
Переделал все исключения

2023-08-18 12:47 UTC, thisisaleksander commented on main-service/src/main/resources/schema.sql
Добавил где нужно

2023-08-19 05:46 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

p.s местами есть дублирование кода этого лучше избегать

-------------------------------

Ну все наше взаимодействие подходит к концу, желаю удачи в работе!

Если будет  желание общаться, работать вместе или обсудить интересный пет-проект, я всегда открыт для этого, мои контакты:
тг https://t.me/kssergey
гитхаб знаешь

2023-08-19 05:53 UTC, merged